"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var wallet_1 = require("./wallet");
var blockchain_1 = require("./blockchain");
var blockchain = blockchain_1.default.instance;
var satoshi = new wallet_1.default();
var eva = new wallet_1.default();
satoshi.sendMoney(50, eva.publicKey);
console.log(blockchain_1.default);
blockchain.minePendingTransactions(satoshi.publicKey);
console.log(blockchain.getTotalBalanceOfAddress(satoshi.publicKey));
